global:
  css:
    base:
      # css/root.css: { weight: -200 }
      css/base/base.css: {}
      css/base/image.css: {}
      css/base/list.css: {}
      css/base/nav.css: {}
      css/base/table.css: {}
    layout:
      css/layout/layout.css: {}
      # css/layout/layout-admin.css: {}
    theme:
      css/theme/eleven.css: { weight: -20}
      css/theme/typography.css: {}
      css/theme/jquery-ui.css: {}
      css/theme/a11y.css: {}
    component:
      css/component/icon.css: {}
      css/component/help.css: {}
      css/component/github.css: {}
      templates/component/button/link-button.css: {}
  js:
    js/eleven.js: {}
  dependencies:
    - system/admin
    - core/modernizr
    - core/jquery.cookie
# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------

# jquery_ui:
#   css:
#     theme:
      # templates/jquery_ui/jquery_ui.css: {}


card:
  css:
    theme:
      templates/layout-landing/card.css: {weight: -20}
      templates/layout-landing/card-icons.css: {}

# card layout
card.layout:
  css:
    theme:
      templates/component/navigation/cardlayout/cardlayout.css: {}
  js:
    templates/component/navigation/cardlayout/cardlayout.js: {}

# ------------------------------------------------------------------------------
# System
# ------------------------------------------------------------------------------
messages:
  css:
    theme:
      templates/component/messages/messages.css: {}
  js:
    templates/component/messages/messages.js: {}
  dependencies:
    - core/drupal
    - core/drupalSettings
    - core/jquery.once

shortcut:
  css:
    theme:
      templates/component/shortcut/shortcut.css: {}

progress:
  css:
    theme:
      templates/component/progress/progress-bar.css: {}

status.report:
  css:
    theme:
      templates/layout-landing/reports/status/report.css: {}
# ------------------------------------------------------------------------------
# Admin landing pages
# ------------------------------------------------------------------------------
admin.config:
  css:
    theme:
      templates/layout-landing/config/admin-config.css: {}

blocklayout:
  css:
    theme:
      templates/layout-landing/block/block-layout.css: {}
# ------------------------------------------------------------------------------
# navigation
# ------------------------------------------------------------------------------
nav.breadcrumb:
  css:
    theme:
      templates/component/navigation/breadcrumb/breadcrumb.css: {}

nav.tabs:
  css:
    theme:
      templates/component/navigation/tabs/tabs.css: {}
      templates/component/navigation/localtask/localtask.css: {}
      templates/component/navigation/localtask/localtask-icons.css: {}

nav.tabs.icon:
  css:
    theme:
      templates/component/navigation/tabs/tabs-icon.css: {}

nav.dropbutton.smallbutton:
  css:
    theme:
      templates/component/navigation/dropbutton/smallbuttons.css: {}

nav.pager:
  css:
    theme:
      templates/component/navigation/pager/pager.css: {}
# ------------------------------------------------------------------------------
# Forms
# ------------------------------------------------------------------------------
form.form:
  css:
    theme:
      templates/component/form/form.css: {}
      templates/component/form/details/form-details.css: {}
      templates/component/form/fieldset/form-fieldset.css: {}
      templates/component/form/textarea/form-textarea.css: {}
      templates/component/form/input/form-input.css: {}
      templates/component/form/checkbox/form-checkbox.css: {}
      templates/component/form/radio/form-radio.css: {}
      templates/component/form/select/form-select.css: {}

form.file:
  css:
    theme:
      templates/component/form/input-file/form-input-file.css: {}
      templates/component/form/input-file/form-input-file.icons.css: {}
  js:
    templates/component/form/input-file/form-input-file.js: {}

button:
  css:
    theme:
      templates/component/button/button/form-button.css: {}
      templates/component/button/button/form-input-submit.css: {}
      templates/component/button/button/form-input-reset.css: {}

button.action:
  css:
    theme:
      templates/component/button/button-action/button-action.css: {}

# ------------------------------------------------------------------------------
# table
# ------------------------------------------------------------------------------
table.responsive:
  css:
    theme:
      templates/component/table/table-responsive.css: {}
  js:
    templates/component/table/table.js: {}

table.admin:
  css:
    theme:
      templates/component/table/table-admin.css: {}

table.drag:
  css:
    theme:
      templates/component/table/table-drag.css: {}
  js:
    templates/component/table/table-drag.js: {}

# ------------------------------------------------------------------------------
# views
# ------------------------------------------------------------------------------
views:
  css:
    theme:
      templates/layout-landing/views/viewsui/views-admin.css: {}

views.cards:
  css:
    theme:
      templates/layout-landing/views/cards/structure-table-views.css: {}

views.exposed:
  css:
    theme:
      templates/component/views/exposed/views-exposed-form.css: {}
  js:
      templates/component/views/exposed/views-exposed-form.js: {}

# ------------------------------------------------------------------------------
# Modules
# ------------------------------------------------------------------------------
modules:
  css:
    theme:
      templates/layout-landing/modules/modules.css: {}
      templates/layout-landing/modules-icons.css: {}


# ------------------------------------------------------------------------------
# Modules
# ------------------------------------------------------------------------------
permissions:
  css:
    theme:
      templates/layout-landing/permissions/permissions.css: {}

# ------------------------------------------------------------------------------
# themes
# ------------------------------------------------------------------------------
themes:
  css:
    theme:
      templates/layout-landing/themes/themes.css: {}

# ------------------------------------------------------------------------------
# node edit
# ------------------------------------------------------------------------------
node.edit:
  css:
    theme:
      templates/layout-landing/node/node-edit-form.css: {}
  js:
    templates/layout-landing/node/node-edit-form.js: {}


# ------------------------------------------------------------------------------
# Here be dragons...
# ------------------------------------------------------------------------------
dragons:
  css:
    theme:
      css/dragons.css: {}
